@id=f3663d91-0cce-408d-8819-faa65dd280e6

PUT http://localhost:5219/breakfast/{{id}}
Content-Type: application/json

{
    "name": "Vegan",
    "description": "Vegan everything! Join us for a healthy breakfast..",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal", 
        "Avocado Toast",
        "Omelette", 
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}

###
PUT http://localhost:5067/breakfast/{{id}}
Content-Type: application/json

{
    "name": "Vegan",
    "description": "Vegan everything! Join us for a healthy breakfast..",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal", 
        "Avocado Toast",
        "Omelette", 
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}